name: everyday_lilly
description: "Everyday Lilly"
publish_to: 'none'
version: 12.0.0+12

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  video_player: ^2.9.1
  cupertino_icons: ^1.0.8
  image_picker: ^1.2.0
  path_provider: ^2.1.1
  photo_view: ^0.14.0
  intl: ^0.19.0
  flutter_local_notifications: ^19.4.2
  share_plus: ^7.2.2
  archive: ^3.6.1
  shared_preferences: ^2.3.2
  flutter_timezone: ^5.0.0
  permission_handler: ^11.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.1

flutter_icons:
  android: true
  ios: false
  image_path: assets/icon.png

flutter:
  uses-material-design: true
  assets:
    - assets/icon.png
    - assets/lily_background.jpg
    - assets/backgrounds/
    - assets/backgrounds/night/
    - assets/backgrounds/evening/
    - assets/backgrounds/afternoon/
    - assets/backgrounds/morning/
    - assets/backgrounds/front_page/
    - assets/quotes/motivational_quotes.txt
    - assets/rewards/
    - assets/achievements/
    - assets/icons/
