name: everyday_lilly
description: "Everyday Lilly"
publish_to: 'none'
version: 2.0.0+2

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  image_picker: ^1.2.0
  path_provider: ^2.1.5
  photo_view: ^0.15.0
  intl: ^0.20.2
  flutter_local_notifications: ^19.4.2
  share_plus: ^12.0.0
  archive: ^4.0.7
  shared_preferences: ^2.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
